### ISSUE TITLE
theta estimation 

### ISSUE THREAD

**Issue by kiminh** [XiaochenWang-PSU/BHNS_Cross_Encoder#1]
hi, thanks a lot for your work. I want to figure out whether the hard negative sampling implementation accords to the paper.

**Comment by XiaochenWang-PSU** [comment]
Hi, thanks for raising the concern. You may find that we have a class namely Efficient_Hard_negative_generator() in the FNE.py file. Given that there is almost no duplicated products appearing within a batch, the summation operation of Eq. (6) can be omitted for the efficiency purpose without any tradeoff of effectiveness. Therefore, you can regard the Efficient_Hard_negative_generator() function as the version we would like to recommend, even though the implementation is slightly different.

**Comment by kiminh** [comment]
appreciate for your reply
